"""审计取证授权与程序留痕：领域资料读取与服务接口。"""

from .access import Permission, Principal, Role
from .clock import ManualClock, SystemClock
from .context import load_context
from .errors import (
    ConflictError,
    DomainError,
    NotFoundError,
    PermissionDenied,
    ValidationError,
)
from .models import (
    KNOWN_DOMAINS,
    AccessEntry,
    AccountQuery,
    Case,
    CaseDomain,
    DeadlineItem,
    DeadlineQueue,
    DeadlineStatus,
    Delivery,
    DeliveryOutcome,
    DisputeStatus,
    DocumentKind,
    DocumentState,
    DocumentVersion,
    EvidenceDispute,
    EvidenceExplanation,
    ExpansionState,
    QueryReceipt,
    RecordCategory,
    RecordVersion,
    RestrictedRecord,
    ScopeExpansion,
    Seal,
)
from .service import (
    AuditService,
    CaseFileView,
    CommitResult,
    Operation,
    op_apply_scope_version,
    op_register_evidence,
    op_seal_materials,
)
from .store import EventStore

__all__ = [
    "load_context",
    "Permission",
    "Principal",
    "Role",
    "ManualClock",
    "SystemClock",
    "DomainError",
    "PermissionDenied",
    "NotFoundError",
    "ValidationError",
    "ConflictError",
    "KNOWN_DOMAINS",
    "AccessEntry",
    "AccountQuery",
    "Case",
    "CaseDomain",
    "DeadlineItem",
    "DeadlineQueue",
    "DeadlineStatus",
    "Delivery",
    "DeliveryOutcome",
    "DisputeStatus",
    "DocumentKind",
    "DocumentState",
    "DocumentVersion",
    "EvidenceDispute",
    "EvidenceExplanation",
    "ExpansionState",
    "QueryReceipt",
    "RecordCategory",
    "RecordVersion",
    "RestrictedRecord",
    "ScopeExpansion",
    "Seal",
    "AuditService",
    "CaseFileView",
    "CommitResult",
    "Operation",
    "op_apply_scope_version",
    "op_register_evidence",
    "op_seal_materials",
    "EventStore",
]
